namespace Subify.Api.Features.Categories.CreateCategories;

using Subify.Domain.Models.Entities.Common;
using MediatR;
using Subify.Domain.Models.Entities.Subscriptions;
using Subify.Domain.Shared;
using Subify.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
// using Microsoft.Extensions.Caching.Distributed; // To be added if IDistributedCache is registered later
using System; // For DateTimeOffset.UtcNow
using System.Threading; // For CancellationToken
using System.Threading.Tasks; // For Task

public class CreateCategoryHandler : IRequestHandler<CreateCategoryCommand, Result<CreateCategoryResponse>>
{
    private readonly SubifyDbContext _context;
    // private readonly IDistributedCache _cache; // To be injected if IDistributedCache is registered later

    public CreateCategoryHandler(SubifyDbContext context /*, IDistributedCache cache */)
    {
        _context = context;
        // _cache = cache;
    }

    public async Task<Result<CreateCategoryResponse>> Handle(CreateCategoryCommand request, CancellationToken cancellationToken)
    {
        // Check for duplicate slug
        if (await _context.Categories.AnyAsync(c => c.Slug == request.Slug, cancellationToken))
        {
            return Result.Failure<CreateCategoryResponse>(Error.Conflict("Category.DuplicateSlug", "Category Conflict", "A category with this slug already exists."));
        }

        var category = new Category
        {
            // ID will be generated by EF Core due to NEWSEQUENTIALID() as per ADR-010
            Slug = request.Slug,
            Icon = request.Icon,
            Color = request.Color,
            SortOrder = request.SortOrder,
            IsDefault = true, // Assuming new categories created via this endpoint are default system categories
            IsActive = true, // Assuming new categories are active by default
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow
        };

        _context.Categories.Add(category);

        // Create resource entries for Turkish and English names
        var resourceTR = new Resource
        {
            // ID will be generated by EF Core
            PageName = "Category",
            Name = request.Slug,
            LanguageCode = "tr",
            Value = request.NameTR,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow
        };
        _context.Resources.Add(resourceTR);

        var resourceEN = new Resource
        {
            // ID will be generated by EF Core
            PageName = "Category",
            Name = request.Slug,
            LanguageCode = "en",
            Value = request.NameEN,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow
        };
        _context.Resources.Add(resourceEN);

        await _context.SaveChangesAsync(cancellationToken);

        // TODO: Invalidate categories cache (e.g., _cache.RemoveAsync("categories:all", cancellationToken);)
        // This requires IDistributedCache or a custom ICacheService to be registered.

        // TODO: Add activity log for category creation
        // _context.ActivityLogs.Add(new ActivityLog { UserId = ..., EntityType = "category", Action = "created", Description = $"Category '{category.Slug}' created." });
        // await _context.SaveChangesAsync(cancellationToken);

        return Result.Success(new CreateCategoryResponse(category.Id));
    }
}