@Subify.Api_HostAddress = http://localhost:5000

### Yeni Kullanıcı Kaydı (Register) Testi
POST {{Subify.Api_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "fullName": "Onur Karakuş",
  "email": "onur@test.com",
  "password": "Password123!"
}

###

### Giriş Yapma (Login) Testi
POST {{Subify.Api_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "onur@test.com",
  "password": "Password123!"
}